{% set name = "opentelemetry-instrumentation-jinja2" %}
{% set version = "0.30b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-jinja2-{{ version }}.tar.gz
  sha256: 3fa46ad43b7fc61657cca2a88010d771cb336a5eb356e50eb15caa2ff8177833

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.30b1
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    # - jinja2 ~=2.7
    # - opentelemetry-test ==0.25b0
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test ==0.25b1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test ==0.25b2
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.26b1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.27b0
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.28b0
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.28b1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.29b0
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.30b0
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.30b1
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-jinja2
  summary: OpenTelemetry jinja2 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
